### ISSUE TITLE
Dúvidas sobre a API

### ISSUE THREAD

**Issue by igortaquary** [Instabuy-Ltda/Instabuy-Selecao#2]
Boa noite, 
não consegui encontrar as marcas dos produtos na API e não encontrei os valores de href nos banners.

![problemaBanner](https://user-images.githubusercontent.com/55813558/87839825-edd1d480-c872-11ea-9bd7-a71b914237b7.png)

**Comment by guilodron** [comment]
Estou enfrentando o mesmo problema.

![image](https://user-images.githubusercontent.com/44059561/87839915-5de05a80-c873-11ea-9a0b-82c6f9877f62.png)

**Comment by Cayke** [comment]
Se o href estiver vazio nao linkar o banner.
Marca é a chave **brand**, opcional.

**Comment by lucaspmarra** [comment]
Também não há a chave **brand**, da marca.

![image](https://user-images.githubusercontent.com/30451874/87844670-c04a5280-c895-11ea-968d-2522c6b2d717.png)

**Comment by Cayke** [comment]
Atualizado url base dos banners
