### ISSUE TITLE
Ausência de marca dos produtos

### ISSUE THREAD

**Issue by luigiminardim** [Instabuy-Ltda/Instabuy-Selecao#3]
Estou fazendo o teste para julho de 2020 e estou seguindo os passos para utilizar a API, porém, não encontrei nenhum atributo referente à marca dos protudos na resposta da request.

**Comment by Joaovjs** [comment]
O atributo referente as marcas é o "brand", porém ele é opcional, então pode ser que nem todos os produtos o tenha. Nesse caso, não se preocupe em apresenta-lo, pode desconsiderar.
