### ISSUE TITLE
Please provide API Key

### ISSUE THREAD

**Issue by RhuanBorgesnr** [Instabuy-Ltda/Instabuy-Selecao#4]
**Bom dia, De acordo com a documentação a autenticação e usado API-KEY, passei ela no cabeçalho mas está me retornando 
401 "Unauthorized".**

**Erro abaixo que está me retornando.**
[https://imgur.com/aE4uQOy](url)

**Comment by Cayke** [comment]
@RhuanBorgesnr voce está enviando a api key de maneira errada. Enviar com nome da chave **api-key** no header da request


curl -X 'PUT' \
  'https://api.instabuy.com.br/store/products' \
  -H 'accept: application/json' \
  -H 'api-key: UgjUpN-xUTRXe_47Edmg94MqDb-3a2AJqo1iZPtJu8A'

**Comment by RhuanBorgesnr** [comment]
Ok, achava que o python não reconheceria esse código.

**Comment by Cayke** [comment]
O codigo que eu enviei nao é python. Foi apenas um exemplo para voce ver que deve enviar a chave de autenticacao como um parametro do header com nome api-key.
