### ISSUE TITLE
API Key 2023

### ISSUE THREAD

**Issue by Toskosz** [Instabuy-Ltda/Instabuy-Selecao#5]
Gostaria de confirmar que a chave de API fornecida para o teste de 2023 está correta.

Tentei replicar o request da documentação mas não consegui.

![Untitled](https://user-images.githubusercontent.com/49496909/220786299-360faffb-cd77-4ec6-a1d0-a013dc7d5b8e.png)

**Comment by Cayke** [comment]
@Toskosz Tenta com a chave ZpokVglRKZqmC89AyQhQt7fe893b2nXix2CL2iVhKDc

**Comment by Toskosz** [comment]
Essa funcionou, obrigado!
