### ISSUE TITLE
Problema com CORS

### ISSUE THREAD

**Issue by TomazDimas** [Instabuy-Ltda/Instabuy-Selecao#6]
Estou tendo problemas ao realizar a requisição a API, normalmente ela funciona, mas após algumas requisições, surge um problema dede CORS, que após algum tempo desaparece e as requisições voltam a funcionar normalmente.

`Access to XMLHttpRequest at 'https://api.instabuy.com.br/apiv3/layout?subdomain=supermercado' from origin 'http://localhost:3000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:4200' that is not equal to the supplied origin.`

Este é o erro que aparece no console da aplicação, procurei na documentação algo sobre autenticação e CORS mas não encontrei nada, este problema pode ser algo que fiz de errado na minha aplicação? Ou é algo específico da API?

**Comment by Cayke** [comment]
@TomazDimas Tenta rodar sua aplicação na porta 4200. Dessa forma acredito que irá funcionar.

**Comment by TomazDimas** [comment]
Obrigado pela ajuda, Cayke! Troquei a porta da aplicação mas o erro continuou, mudando o texto do erro:

`Access to XMLHttpRequest at 'https://api.instabuy.com.br/apiv3/layout?subdomain=supermercado' from origin 'http://localhost:4200' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'http://localhost:3000' that is not equal to the supplied origin.`

Eu achei estranho porque o erro acontece algumas vezes só, depois de fazer algumas requisições ele aparece, e depois de esperar um tempo ele some.

**Comment by Cayke** [comment]
@luigiminardim Da um help aqui. Estao tendo problemas com CORS.

**Comment by luigiminardim** [comment]
@Cayke , acredito que teremos que pedir para o pessoal adicionar um novo parâmetro nas requisições, o qual informa o id dentro do Github, dessa forma, poderemos mandar o header Access-Control-Allow-Origin diferente de acordo com o usuário.

Exemplo:
```sh
GET https://api.instabuy.com.br/apiv3/layout?github_id=luigiminardim&subdomain=supermercado
```

**Comment by Cayke** [comment]
@TomazDimas Faz essa sugestao ai do Luigi. Mandar nas requests o parametro github_id e o seu ID de usuario.
Veja se dessa forma voce para de ter problema de CORS

**Comment by TomazDimas** [comment]
Show! Coloquei aqui e parece que resolveu! Obrigado pela ajuda, pessoal.
