### ISSUE TITLE
problema com a api-key fornecida (integração-ago-23)

### ISSUE THREAD

**Issue by douglas-s29** [Instabuy-Ltda/Instabuy-Selecao#7]
ao enviar solicitação para a api ao enviar me retonar o erro invalid key

![erro_401](https://github.com/Instabuy-Ltda/Instabuy-Selecao/assets/101368605/9fd7d72d-01af-46f1-af5c-7934f9959a7c)

Outra duvida é se após enviar os dados para a api devo armazenar a resposta da mesma em outro csv. E se o csv forneciso vai preencher os campos vazios.

**Comment by Cayke** [comment]
@douglas-s29 Gerei uma nova API-KEY 
Mq1EWAXiHwraLIQgfq4stmUxKiM6VpC5Xd9o3wuX1Go

**Comment by Cayke** [comment]
Sobre armazenar a resposta em outro CSV nao é necessario.
A segunda pergunta nao entendi.

**Comment by douglas-s29** [comment]
Perdão ficou meio confuso.

A segunda pergunta é referente o csv fornecido items, estava verificando ele e alguns campos encontram-se vazios, após mandar os dados para a api eles atualizam?

**Comment by douglas-s29** [comment]
> @douglas-s29 Gerei uma nova API-KEY 
> 
> Mq1EWAXiHwraLIQgfq4stmUxKiM6VpC5Xd9o3wuX1Go

Deu certo obrigado!
